### ISSUE TITLE
this keeps popping up when I try to watch a video hosted on openload

### ISSUE THREAD

**Issue by safiyyah237** [zant95/hBlock#10]
Please add these, I don't think I go through a day without them popping up
www.simple2date.com
http://34.250.229.112/

**Comment by zant95** [comment]
Currently I don't maintain my own list, you will have better luck if you ask any of my [sources](/zant95/hBlock/blob/master/README.md#sources) to add that domain. In the meantime you can manually add that domain to my script.

**Comment by zant95** [comment]
Spam404 has a submission form: www.spam404.com/report.html
