### ISSUE TITLE
Custom blacklisting sources

### ISSUE THREAD

**Issue by matrixik** [zant95/hBlock#11]
Hello, thank you for nice script to make our lives better.

Would be nice to have possibility to specify custom blacklisting sources that would be used instead of build in.
I would like to use https://github.com/StevenBlack/hosts that already have many concatenated by type and ready to use.

**Comment by matrixik** [comment]
Not sure how to make it work with systemd service files without editing them by hand.

**Comment by zant95** [comment]
You can currently do something like:
```sh
./hblock -S "$(cat sources.txt)"
```
This will override the entire list of sources within the script.

**Comment by matrixik** [comment]
I must have missed this arg, thank you.
