### ISSUE TITLE
Whitelist and blacklist from files

### ISSUE THREAD

**Issue by matrixik** [zant95/hBlock#13]
Maybe you could add option to load whitelisted and blacklisted domains from files.
This way we would be able to share them between many computers.

For default it could be `$HOME/.hblock_whitelist` and `$HOME/.hblock_blacklist`.
But I'm not sure how to make it work with systemd service files.

**Comment by zant95** [comment]
You can currently do something like:
```sh
./hblock -W "$(cat whitelist.txt)" -B "$(cat blacklist.txt)"
```

**Comment by matrixik** [comment]
Did not though about this, thank you.
