### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by veloute** [zant95/hBlock#14]
Is the whitelist consistent or is it a once-per-command flag?
If there isn't a way to make the whitelist permanent by default, is there a way to change it without having to go into the script and add domains manually every time?

**Comment by zant95** [comment]
It's a once-per-command flag, but you can define the whitelist in an external file and call hblock with these arguments:
```sh
./hblock -W "$(cat whitelist.txt)"
```
Does this solve your problem?

**Comment by veloute** [comment]
Yes, this solution fits my needs perfectly. Thanks. 👍
