### ISSUE TITLE
feature request search function

### ISSUE THREAD

**Issue by illucent** [zant95/hBlock#15]
any plans to add search functionality inside lists?
$ grep -i "analytics.google.com" /etc/hosts
$ hblock -W analytics.google.com

**Comment by zant95** [comment]
If I understand correctly, do you mean to search in which source an entry appears?

**Comment by illucent** [comment]
just to search whether entry is already there

**Comment by zant95** [comment]
I think this is outside the scope of the project. Why not just use grep?

**Comment by illucent** [comment]
Grep is of course awesome; eg. in case when sometimes website is blocked and user wants to check whether it is hosts file or extension issue or network. I can write it myself later and offer to review / include.

**Comment by zant95** [comment]
I would like to keep this script as simple as possible and not add new features unless absolutely necessary.
