### ISSUE TITLE
Making a time-stamped backup of /etc/hosts before overwriting it.

### ISSUE THREAD

**Issue by ZeBaal** [zant95/hBlock#4]
The title pretty sums it all, how about making a time-stamped backup of the hosts file before overwriting it?

**Comment by zant95** [comment]
This is not the behavior I want, because I use this script on my phone. But I can implement the backup as an optional argument.

**Comment by zant95** [comment]
Fixed (0e6aeb4948b013d1f3009f9f40897582a4b23988).
