### ISSUE TITLE
Android - zip file invalid

### ISSUE THREAD

**Issue by Temeez** [zant95/hBlock#5]
After I installed curl and zip, I get this.

http://i.imgur.com/91JZSIn.png

Any ideas?

**Comment by zant95** [comment]
Ironically, the 'T' argument added to check the integrity of the zip file is causing the failure. I think it is a Termux bug, since its zip command list the 'T' argument as valid but it is not working.

**Comment by Temeez** [comment]
What terminal emulator are you using in the preview_android.png? I tried several others but none of them do anything after the curl command.

**Comment by zant95** [comment]
It is a local terminal in [JuiceSSH](https://play.google.com/store/apps/details?id=com.sonelli.juicessh). You need a complete BusyBox installation to run my script (which CM already provides).

If you do not want to install BusyBox, Termux already provides the tools that you need to run my script, it is just that there is a bug with their zip command.

If you change [this line](https://github.com/zant95/hBlock/blob/d46cfd4c2f158eb2b18d8d5ea39f379b55544dbc/android/make_flashable_zip_from_remote.sh#L32) removing the 'T' argument, it will work with Termux.
`zip -r "$HOME/hblock.zip" .`

**Comment by Temeez** [comment]
Thanks. Got it working by forking and removing the 'T' argument.
