### ISSUE TITLE
Download List link not available

### ISSUE THREAD

**Issue by tmountney** [zant95/hBlock#7]
The link:
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
is not working - not available...
I commented it out but am wondering if there is a alternative/replacement link..?

**Comment by zant95** [comment]
It is up again, although to avoid these problems I am planning to create a mirror of each source.

**Comment by zant95** [comment]
Done (0b395dc).

**Comment by tmountney** [comment]
Dear Héctor,

Nice work! Very nice..! Really appreciate thiis! Thank you...

Keeping the hosts file up-to-date manually is a hassle, so scheduling hBlock is a real benefit.

I was unaware of the ransom ware site ransomwaretracker.abuse.ch, the one that was failing.  Though there was a problem, for me that failure was educational.

A question about the intent and setting of $ignoreDownloadError …

- why is the value of ignoreDownloadError set to ‘no’ by default?
- what did you intend with ignoreDownloadError – perhaps for testing? Or is there another reason or benefit for setting it to other than ‘no’?

IMHO the fact that a download of some site fails occasionally, resulting in some sites not being included in the generated hosts file, is not fatal as long as there is notification of the failure like you have provided. For me having ‘most’ of the sites included/updated is better than not having any at all.

Again, thank you for this excellent tool

**Comment by tmountney** [comment]
sorry... forgot in the previous message

On the chance that you might be interested...

I’ve added some other modifications to ‘trap’ and report errors and to lessen/limit the status (printInfo, printAction) output when hblock is run as a cron job.

If interested please let me know and I'll send you my modified version with some explanation notes..

**Comment by zant95** [comment]
Hi,

I prefer the script to fail and wait for all sources to be accessible, since I assume that a previous version of the hosts file exists on the system, but this is a personal preference. If this behavior does not fit your need then you can invoke the script with ```--ignore-download-error```.

On the other hand, I'd glad to see the modifications you've made to the script.

**Comment by tmountney** [comment]
Hi Hector,

Haven't forgotten you and sending additions/modifications. I'm continuing to test, document and clean up the code before I send it to you. I don't think my code is as well designed and clean as yours.

There is a reason that I've been working on the scheduling (cron) - I support 5 elderly friends who as users are certainly not knowledgeable re Linux and such things as hosts files and the importance of security so I need to automate hblock as much as possible so I can keep tabs on its status.

Once I'm certain that it works (scheduling) I'll send it..
Again I appreciate hblock and your excellent work...
